### ISSUE TITLE
CSS classes with hyphen character

### ISSUE THREAD

**Issue by agaskell** [garthenweb/parcel-plugin-css-modules-type-generator#3]
Are CSS classes with hyphens supported? I see the correct name in the generated file (CSS class `foo-bar` becomes `fooBar`) but the value of the generated name is `undefined`.

**Comment by garthenweb** [comment]
I implemented the transform for hyphens to be compatible with the webpack loader my team used to generate the `.d.ts` files before. Maybe this was a bad decision.

If I understand you correctly either the types or the variables are wrong when using hyphens and therefore this can be considered a bug, is this correct? Just thinking about whether this would be a breaking change or not, if it is not working at the moment we can easily fix it in a patch version bump!

**Comment by agaskell** [comment]
A little background - I'm coming from preact-cli's TypeScript generator, which uses the webpack loader [typings-for-css-modules-loader](https://github.com/Jimdo/typings-for-css-modules-loader). CSS class names with hyphens are supported in this project but I didn't want to make an assumption about this project so I asked :smile:.

I don't think fixing this would would be a breaking change, but I haven't dug into the code.

Here's an example css file:
```
.foo {
  color: green;
}

.foo-bar {
  color: red;
}
```
Generated d.ts (looks good I think):
```
export const foo: string;
export const fooBar: string;
```

Trying to use in a component:
```
import * as style from './style.css';
import { foo, fooBar } from './style.css';

console.log('style.foo', style.foo);
console.log('style.fooBar', style.fooBar);
console.log('style["foo-bar"]', style["foo-bar"]);
console.log('foo', foo);
console.log('fooBar', fooBar);
```

Console output:
```
style.foo _foo_b8c67
style.fooBar undefined
style["foo-bar"] _foo-bar_b8c67
foo _foo_b8c67
fooBar undefined
```

Expected console output:
```
style.foo _foo_b8c67
style.fooBar _foo-bar_b8c67
style["foo-bar"] _foo-bar_b8c67 (I don't really care if this one works or not)
foo _foo_b8c67
fooBar _foo-bar_b8c67
```

**Comment by garthenweb** [comment]
Ah okay, thank you for the example.

Looks like your issue is not directly about the types this plugin generated but about the output parcel generates.
Maybe this issue helps https://github.com/parcel-bundler/parcel/issues/968. Also, Postcss seems to allow a `camelCase` configuration: https://github.com/css-modules/postcss-modules#camel-cased-classes.

Anyhow, based on your example it looks like the types are actually not correct, as parcel does not generate `fooBar` but `foo-bar` by default. I think we can extend the plugin to respect the `camelCase` option for CSS modules which would not result in a breaking change but a bugfix.

In case you are going to test the `camelCase` option, please let me know if it is working as expected!

**Comment by garthenweb** [comment]
@agaskell I just released a new version with respects the `camelCase` option of the postcss modules plugin. Happy to hear if it solves your issue.

**Comment by agaskell** [comment]
@garthenweb that worked, thank you! It took me a while to figure out that I needed to add a `plugins` property to my .postcssrc. Would you accept a PR that describes how to configure camel case classes with this plugin?

**Comment by garthenweb** [comment]
Glad to hear!
I am not sure whether we should document CSS modules config within this plugin, as it is not about creating the class names but only about the machting types.
Maybe it would be more helpful to create a PR to the Parcel website to better explain how to work with postcss modules plugin, as this is not described there at all and would also help none TS users: https://parceljs.org/css.html#postcss

**Comment by rfgamaral** [comment]
> 
> 
> @agaskell I just released a new version with respects the `camelCase` option of the postcss modules plugin. Happy to hear if it solves your issue.

I've realized you're not actually respecting the `camelCase` property but generating both `camelCase` and `kebab-case` for CSS classes with hyphens when `camelCase: true` but only generating `kebab-case` when `camelCase: false`.

To truly respect that property, you either generate one or the other, never both. Now, this current behavior could be 100% intentional and I have nothing against it. But in case it's not, assume this as a bug report.

**Comment by garthenweb** [comment]
It is intentional. This plugin respects whatever parcel/ postcss generates, with this option activated they are exposing both classes, therefore both are exported in the types. If you think this is not the correct behavior, you might want to open an issue for the postcss-modules plugin.

**Comment by rfgamaral** [comment]
> with this option activated they are exposing both classes

I could swear the bold statement was false but I might be in the wrong. I'll double check later, but you are probably right. Sorry for the confusion.
